### ISSUE TITLE
Platform-independent file path separator fixes

### ISSUE THREAD

**Issue by jgerrish** [chyroc/github2dropbox#2]
Thank you for this great application and action, I'm getting ready to use parts of it for backups.

I have a couple fixes I would be happy to submit a PR for.  Let me know and I can submit it, or if you have any better ideas on these changes.

The code uses forward slashes '/' throughout the code,which is fine for the default Ubuntu and Docker targets, but I'd like to get it working for other systems too. There are also some potential issues sanitizing return values from the GitHub API.

Changing this line:
	dir := filepath.Dir(genPath(dataList[0]))
to this:
	dir := filepath.Dir(filepath.FromSlash(genPath(dataList[0])))

in run.go gets forward paths working on Windows for example.

There's also a strings.replaceAll in save.go that would need to be changed:

func replaceSeparatorsFilePath(path string, replacement string) string {
	path = strings.ReplaceAll(path, fmt.Sprintf("%c", os.PathSeparator), replacement)
	return strings.ReplaceAll(path, "/", replacement)
}

Finally, I sanitize returns from the GitHub API like this:
func (r *Backup) repoJsonPath(repo *github.Repository) string {
	return fmt.Sprintf("%s/%s/repo/%s/%s.json", r.BackupDir, sanitizedFilePath(r.self.GetLogin()), sanitizedFilePath(repo.GetName()), sanitizedFilePath(repo.GetName()))
}

// Check if a string is safe for substituting in a path.
// If the string has substrings like ../ in it, it's not safe.
// Use OS-agnostic parsing function filepath.Split
// If we're getting unsafe strings, things have gone wrong, just panic.
// If things are good, return the string.
func sanitizedFilePath(variable string) string {
	dir, file := filepath.Split(variable)

	if dir == "" {
		return file
	} else {
		panic(fmt.Sprintf("Unsafe result returned from github API: %s", variable))
	}
}

And just panic if there is a forward slash in repo.GetName() or something.  This will probably never happen, but it doesn't hurt to be careful there.  You may not want to panic and instead substitute an underscore.

Let me know if you want me to submit a PR.  Thank you for your time and this project.

**Comment by chyroc** [comment]
@jgerrish Hi, thanks for your issue, I think your suggestion is very valuable, if you have time, you are welcome to submit a github pr to deal with this issue, thank you.

**Comment by jgerrish** [comment]
Thank you again for the tool, I'll put together a PR and submit it tomorrow.

**Comment by chyroc** [comment]
fixed.
